# Generated by Django 4.2.23 on 2025-07-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_transcription_model_to_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='api_credentials',
            field=models.TextField(blank=True, help_text='Encrypted API credentials'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='api_endpoint',
            field=models.URLField(blank=True, help_text='Custom API endpoint URL', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='api_model',
            field=models.CharField(blank=True, help_text='API-specific model name', max_length=50),
        ),
        migrations.AddField(
            model_name='meeting',
            name='transcription_provider',
            field=models.CharField(choices=[('local', 'Local Whisper Models'), ('openai', 'OpenAI Whisper API'), ('assemblyai', 'AssemblyAI'), ('deepgram', 'Deepgram'), ('custom', 'Custom API Endpoint')], default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='transcription_model',
            field=models.CharField(choices=[('tiny', 'Tiny'), ('base', 'Base'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('large-v2', 'Large V2'), ('large-v3', 'Large V3')], default='medium', help_text='For local provider: Whisper model. For APIs: provider-specific model', max_length=50),
        ),
    ]
