# Generated by Django 4.2.23 on 2025-07-07 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_transcription_provider_to_meeting'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS core_audiochunk;",
            reverse_sql="-- AudioChunk table will be recreated if migration is reversed"
        ),
    ]
