# Generated by Django 4.2.23 on 2025-07-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250707_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='transcription_provider',
            field=models.CharField(choices=[('local', 'Local Whisper Models'), ('openai', 'OpenAI Whisper API'), ('assemblyai', 'AssemblyAI'), ('deepgram', 'Deepgram'), ('n8n', 'n8n Workflow'), ('custom', 'Custom API Endpoint')], default='local', max_length=20),
        ),
    ]
