# Generated by Django 4.2.23 on 2025-07-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_meeting_transcription_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='transcription_model',
            field=models.CharField(choices=[('tiny', 'Tiny'), ('base', 'Base'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('large-v2', 'Large V2'), ('large-v3', 'Large V3'), ('thonburian-medium', 'Thonburian Medium - Thai Optimized'), ('thonburian-large', 'Thonburian Large - Thai Optimized')], default='medium', help_text='For local provider: Whisper model. For APIs: provider-specific model', max_length=50),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='whisper_model',
            field=models.CharField(choices=[('tiny', 'Tiny'), ('base', 'Base'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('large-v2', 'Large V2'), ('large-v3', 'Large V3'), ('thonburian-medium', 'Thonburian Medium - Thai Optimized'), ('thonburian-large', 'Thonburian Large - Thai Optimized')], default='base', max_length=20),
        ),
    ]
