# Generated by Django 4.2.23 on 2025-07-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_meeting_transcription_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, help_text='When actual transcription processing began', null=True),
        ),
    ]
